# rocksdb_binding.pyi

from typing import Optional, Dict, List

class RocksDB:
    def __init__(self, blobdb=False) -> None: ...
    def open(self, db_path: str) -> bool: ...
    def put(self, key: bytes, value: bytes) -> bool: ...
    def get(self, key: bytes) -> Optional[bytes]: ...
    def probe(self, key: bytes) -> bool: ...
    def multiget(self, keys: List[bytes]) -> Dict[bytes, Optional[bytes]]: ...
    def batch_put(self, keys: List[bytes], values: List[bytes]) -> bool: ...
    def delete_key(self, key: bytes) -> bool: ...
    def set_custom_option(self, value: int) -> None: ...

class Options:
    def __init__(self) -> None: ...
    create_if_missing: bool
    max_open_files: int
